apiVersion: v1
kind: Service
metadata:
  name: micro
  labels:
    service: microapi    
spec:
  type: LoadBalancer
  # type: NodePort
  ports:
  - name: api-http
    port: 80
    targetPort: "api-port"
    protocol: TCP
  selector:
    app: micro
