apiVersion: v1
kind: Service
metadata:
  name: greeter
  labels:    
    service: greeter
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    app: greeter