apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: greeter
  labels:
    deployment: greeter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: greeter
  template:
    metadata:
      labels:
        app: greeter        
    spec:
      containers:
      - name: greeter
        image: ilovelili/greeter-consul:0.4
        command: [
          "./micro-consul",
        ]
        env:        
        - name: MICRO_REGISTRY
          value: "consul"
        - name: MICRO_REGISTRY_ADDRESS          
          value: "svc-consul:8500"